[package]
name = "rust-sudoku-solver"
version = "0.2.1"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
sudoku = { git = "https://github.com/Rrogntudju/sudoku-rs.git", features = ["test"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
