[package]
name = "rust-sudoku-solver"
version = "0.2.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
sudoku = { git = "https://github.com/Rrogntudju/sudoku-rs.git", features = ["test"] }

[profile.release]
opt-level = 3
lto = "fat" 
codegen-units = 1
