[package]
name = "rust-sudoku-solver"
version = "0.2.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
rand = "0.8"
ahash = "0.7"

[profile.release]
opt-level = 3
lto = "fat" 
codegen-units = 1
